### ISSUE TITLE
KB access token is revoked

### ISSUE THREAD

**Issue by md2manoppello** [crossminer/scava-deployment#104]
https://github.com/crossminer/scava-deployment/blob/da805826b7c1c62fa91a582f4d8751f64b381127/KB/application.properties#L14

Hi @MarcioMateus , the KB token is no longer available because of GitHub policies:

> We noticed that a valid OAuth access token of yours was committed to a public GitHub repository. Publicly disclosing a valid access token would allow other people to interact with GitHub on your behalf, potentially altering data, your contact information, and billing data.
As a precautionary measure, we have revoked the OAuth token. A new token will need to be generated in order to continue using OAuth to authenticate to GitHub. Here are a couple of steps you can do to ensure your account security has not been compromised:

The access token is mandatory to add new projects to the KB.
Now, when someone tries to import a new project the KB fails.
Can you help me?
@mhow2  and @valeriocos are asking to import new projects.

**Comment by MarcioMateus** [comment]
Hi @md2manoppello, as I see it the user should provided the GitHub token whenever they want to add a new project. That token will be used to get information about the project. So the API for adding new projects should request the token.

Does it make any sense to you?

**Comment by md2manoppello** [comment]
Thanks @MarcioMateus, it should work! I'll add the GitHub token as parameter to the add project resource.

**Comment by md2manoppello** [comment]
The token is no longer necessary. Now the add project resource takes GitHub token as a parameter.
