### ISSUE TITLE
curl's missing in dashboard image

### ISSUE THREAD

**Issue by mhow2** [crossminer/scava-deployment#106]
@MarcioMateus , since you have switched to the slim version of the python image, curl is not included , as you see at   https://github.com/crossminer/scava-deployment/blob/62a9acbc0fc358b9739a41e3a33773de521dc68c/dashboard/starter.sh#L10

**Comment by MarcioMateus** [comment]
Hi @mhow2 . Thanks for spotting the problem (and the solution). I did a commit (https://github.com/crossminer/scava-deployment/commit/869f39722a2a3867508b5ea67f10a875be085191) to fix it.
