### ISSUE TITLE
dashb-importer must wait for elasticsearch

### ISSUE THREAD

**Issue by acs** [crossminer/scava-deployment#12]
Right now before starting the dashb-importer  it waits for oss-app. 

https://github.com/crossminer/scava-deployment/blob/dashboards/docker-compose.yml#L135

It must also wait for elasticsearch for importing the data from Scava to Elasticsearch

**Comment by MarcioMateus** [comment]
@acs please validate if commit 71c8c31d1dcff4bbababa6ce460209238b838dd6 solves this bug

**Comment by acs** [comment]
> @acs please validate if commit [71c8c31](https://github.com/crossminer/scava-deployment/commit/71c8c31d1dcff4bbababa6ce460209238b838dd6) solves this bug

Comment added to the commit. Probably that commit fixes the problem. But let me test it to be sure. Once I have tested it I will report it here and if it is fixed, I will close this issue. 

Thanks @MarcioMateus !

**Comment by acs** [comment]
I confirm that in a deployment from scratch all has worked as expected so https://github.com/crossminer/scava-deployment/commit/71c8c31d1dcff4bbababa6ce460209238b838dd6  has fixed this issue. Thanks @MarcioMateus
