### ISSUE TITLE
installation is ok but no credentials to sign in

### ISSUE THREAD

**Issue by mhow2** [crossminer/scava-deployment#13]
Hi,
I've been able to start the instance with docker-compose and the yml file provided in the dev branch, and access the service from localhost:9000.
Now, I need some kind of account I guess ? I followed the invitation process and provided my email : do I need to wait for an answer ?

**Comment by tdegueul** [comment]
Hi @mhow2,

The Docker setup normally comes with a database dump that contains a default user:

login: demo@crossminer.org
pwd: crossminer

Please let me know if it works for you.

**Comment by mhow2** [comment]
hi @tdegueul ,
I tried the docker setup this morning (git pull & started the one at `docker-compose-dockerhub.yml`), and I'm unable to log in with the credentials you provided above.

**Comment by mhow2** [comment]
Hi @MarcioMateus , I did follow the steps described in https://github.com/crossminer/scava-deployment/blob/add-api-gateway/README.md. I deployed on a remote server. I did updated the hosts file on the remote server. I had to slightly modify `port` in the `admin-webapp` service to expose another port than 80 (ie: `"8011:80"`) because 80 was already taken on this system. Then I get this :  http://sandbox.ow2.org:8011/login but I am unable to login with admin/admin.

**Comment by mhow2** [comment]
Also tried to 
- update `auth/application.properties` reflecting the public port with (8011) no success
- freeing port 80 on this server and restart the containers from scratch with defaults values - no success
I must miss something.

**Comment by MarcioMateus** [comment]
Hi @mhow2 ,
I never tested the access to the admin from a remote location.
I confirm the I am also unable to authenticate as I receive a "Bad credentials!" message.
However, it seems that @borisbaldassari was able to do some work around as its setup is working (http://ci4.castalia.camp:8000/login).
@borisbaldassari , did you do any modification to the configuration?

**Comment by mhow2** [comment]
I'm able to sign in with a local installation even without modifying the `hosts` file.

**Comment by MarcioMateus** [comment]
@mhow2 Yes, the change to the hosts was to address a issues where I was unable to import new projects.

**Comment by mhow2** [comment]
@MarcioMateus : I see. I was unable to import a new project by URL too (why I click the button to submit it remains greyed out), however creation is OK.

In the end, should I understand the hosts file trick has nothing to do with our "bad credentials" issue ?

When you said earlier:
> I confirm the I am also unable to authenticate as I receive a "Bad credentials!" message.

Were you relating the installation at castalia ?

**Comment by borisbaldassari** [comment]
Hiho,
@MarcioMateus  Late answer: no, I didn't change anything to the base configuration. Apart from changing the hosts file on my host I mean.

**Comment by mhow2** [comment]
@ambpro : I identified an issue specific to my setup : default permissions for newly created file on our systems (here, the docker host) is 640 for files. So my local files pulled from git are 640, then it's added with the same permissions to the container's filesystem : In the end nginx wasn't able to read `externalConfig.json`.

It was then easy to `chmod o+r` the file and rebuild the container. Alternatively, it's possible to add `--chown=root:nginx` to the `ADD` statement.

So there was in fact two issues stacking. The first one is solved by your fix at f8cd734a94bfe109e5f30862cd482c0fdda68ba4 (thanks!) and the second is the one above but it's only specific to my system.
