### ISSUE TITLE
Auth-server does not restart correctly

### ISSUE THREAD

**Issue by MarcioMateus** [crossminer/scava-deployment#19]
@mhow2 said "hi. It seems there is an issue with the auth-server container, when you stop/start the containers stack (`docker-compose -f... up` then Ctrl+C to stop then `docker-compose -f... up` again ), auth-server isn't able to reach mongodb. If you remove the containers completely and restart from scratch it seems to works (`docker-compose -f ... down`, then `up`)"

The visible effect of the above is - among potential others - is you get a "bad credentials" when trying to login to the admin UI.

**Comment by borisbaldassari** [comment]
Hey. I have the same problem even after a down I believe... 
http://ci4.castalia.camp:5601/login

**Comment by MarcioMateus** [comment]
After some tests I realised that this behaviour was caused by restarting problem on oss-db. 

I create a new branch to fix problem: 
https://github.com/crossminer/scava-deployment/tree/fix-oss-db-restart

You can test the latest commit 7554c56

Notice that I reduced the amount of messages produced, so the output is different from the usual.

The startup of the machine is still taking a lot of time. I will to try to improve it a bit.

**Comment by borisbaldassari** [comment]
Fixed on my side! :-)
Thanks @MarcioMateus !

**Comment by mhow2** [comment]
Looks ok for me too ! I suggest we merge.

**Comment by MarcioMateus** [comment]
Fixed on 98065d31d2aef8ea7bd4d632faf7df1b25e85517
