### ISSUE TITLE
ProSoul : model viewer is not visible

### ISSUE THREAD

**Issue by mhow2** [crossminer/scava-deployment#24]
the model viewer is not visible at  http://ci4.castalia.camp:8000/prosoul/viewer and http://wacke.ow2.org:8000/prosoul/viewer
If you look at the network requests/responses from the dev pane, you'll see some 404's.

**Comment by valeriocos** [comment]
The PR https://github.com/Bitergia/prosoul/pull/90 should fix this bug. A docker image is already available with the fix. 
Please @mhow2 @borisbaldassari let me know if the error is gone

**Comment by mhow2** [comment]
Gone for me. Opened #27 for other resources missing.

**Comment by borisbaldassari** [comment]
Fixed for me. Thanks @valeriocos !
