### ISSUE TITLE
KB configuration issue

### ISSUE THREAD

**Issue by md2manoppello** [crossminer/scava-deployment#3]
Jenkins builds KB service platform at http://ci5.castalia.camp:8080/job/scava-knowledgebase/lastSuccessfulBuild/artifact/knowledge-base/org.eclipse.scava.knowledgebase/target/scava.knoledgebase.jar .
KB testing step needs that ```spring.data.mongodb.host``` has ```localhost``` value in ```applicacation.properties```.
Instead, docker kb image needs to set this parameter as ```KB-db```.
@MarcioMateus, did you change this value on http://ci3.castalia.camp/dl/scava.knoledgebase.jar ?

**Comment by md2manoppello** [comment]
@MarcioMateus, @tdegueul  Could we automate KB build for docker image?

**Comment by MarcioMateus** [comment]
This change was introduced in commit 8fb7d0c4edc757d8de2144488814a92a80176f50

To KB docker image downloads the jar built by Jenkins (configured for the `localhost`) and updates the `application.properties` to connect to the `KB-db`.

I did some small tests, but I would be great id you could do a more extensive testing.

**Comment by tdegueul** [comment]
Regarding the automatic generation of Docker images from the CI builds, the images are now (automatically?) pushed to https://hub.docker.com/u/crossminer/; @borisbaldassari took care of that. I don't know how this is realized though, as I haven't seen anything new on the CI server.

**Comment by md2manoppello** [comment]
Thank you!
Can we close this issue?

**Comment by MarcioMateus** [comment]
Yes, I think that the main question is already addressed.
