### ISSUE TITLE
restarting the host causes the scava-deployment_oss-web application to fail to start in its container because RUNNING_PID had not been deleted.

### ISSUE THREAD

**Issue by md2manoppello** [crossminer/scava-deployment#4]
Do you recognize the same issue on restarting oss-web docker container?
A possible solution is described at
https://stackoverflow.com/questions/28351405/restarting-play-application-docker-container-results-in-this-application-is-alr

**Comment by mhow2** [comment]
I second the above:

```
oss-web_1     | Play server process ID is 1
oss-web_1     | This application is already running (Or delete /org-ossmeter-webapp-1.0-SNAPSHOT/RUNNING_PID file).
kb-db_1       | 2018-10-15T14:19:47.765+0000	CROSSMINER.artifact  12.6MB
kb-db_1       | 2018-10-15T14:19:47.765+0000	reading metadata for CROSSMINER.relation from archive 'CROSSMINER.20180906.gz'
kb-db_1       | 2018-10-15T14:19:47.784+0000	restoring CROSSMINER.relation from archive 'CROSSMINER.20180906.gz'
scava-deployment_oss-web_1 exited with code 255
```

I tried deleted the 'web' container and ran `docker-compose up` again with no much success.
However, I can get it back on track by deleting/restart all containers.

**Comment by MarcioMateus** [comment]
This is strange for me. At least I don't remember ever seeing it. 

Can you give more information about the steps to replicate it? For instance, how did you delete or stop the 'oss-web' container?

**Comment by mhow2** [comment]
I can't reproduce in the current deployment shipped at branch `dashboard-plus-admin`.
