### ISSUE TITLE
Duplicated API_GATEWAY_VAR

### ISSUE THREAD

**Issue by tdegueul** [crossminer/scava-deployment#46]
`API_GATEWAY_VAR` definition is duplicated in:

  - https://github.com/crossminer/scava-deployment/blob/dev/docker-compose-build.yml#L31
  - https://github.com/crossminer/scava-deployment/blob/dev/web-admin/Dockerfile#L4

I guess one of them should be removed?

**Comment by ambpro** [comment]
Hi @tdegueul , 
AFAIK, the env-var on the docker-compose file takes precedence over that specified on the Dockerfile. 
Thus, the variable in the Dockerfile is only used at building time and used as default in case that docker-compose do not defines the variable. To allow users to configure during setup time, we need to allow it in the docker-compose. 
This approach will also allow the configuration of pre-built docker images as is the case of the ones in DockerHub

**Comment by tdegueul** [comment]
From the official documentation, I also understand that docker-compose has precedence over Dockerfile for environment variables.

When the user builds the images locally, the docker-compose variable is used. When the user reuses images that are built remotely (from DockerHub), the docker-compose still has precedence, right?

So shouldn't we remove the `API_GATEWAY_VAR` in `web-admin/Dockerfile` since it is never used? Or did I miss something?

**Comment by ambpro** [comment]
> When the user builds the images locally, the docker-compose variable is used. When the user reuses images that are built remotely (from DockerHub), the docker-compose still has precedence, right?

Yes!

> So shouldn't we remove the API_GATEWAY_VAR in web-admin/Dockerfile since it is never used? 

The `API_GATEWAY_VAR` in `web-admin/Dockerfile` is used as a backup solution in a generic case either when the image is used in a standalone mode or the somehow the  `API_GATEWAY_VAR`config is missing in the `docker-compose`

**Comment by tdegueul** [comment]
Ok, the standalone mode sort of makes sense! Thanks for the explanation!
