### ISSUE TITLE
prosoul's database gets corrupted when some data are imported to ES

### ISSUE THREAD

**Issue by mhow2** [crossminer/scava-deployment#50]
What I observe is at some point in the workflow, when going to` /prosoul/editor` I get an error 500. And the logs reports `sqlite3.IntegrityError: UNIQUE constraint failed: prosoul_metricdata.id`

See how to reproduce the issue:
- deploy a fresh crossminer stack
- go to `/prosoul/editor`, login in when required. You should see the `edit` view as expected with the three panes (goal, attributes, metrics).
- now, within the SCAVA admin UI: add a `githubToken` property (with a valid token of couse)
- Provision a project : https://github.com/docdoku/docdoku-plm
- Add a task. You can tick one metric only and any period (a few days is enough).
- Wait for the scava2es thing to run.
- reload `/prosoul/editor` : it will fail with 500. From there you get the error `sqlite3.IntegrityError: UNIQUE constraint failed: prosoul_metricdata.id`

**Comment by valeriocos** [comment]
@mhow2 a new version of prosoul is being generated. Once this is done, would you mind check on your side, thanks ?

**Comment by mhow2** [comment]
I've deployed the new version, it seems to work !

**Comment by valeriocos** [comment]
Thank you for the quick feedback @mhow2 and @dlumbrer for the fix.
