### ISSUE TITLE
setup instance deployment branches (beta, ow2...)

### ISSUE THREAD

**Issue by mhow2** [crossminer/scava-deployment#81]
The idea is to track and share the various docker deployment configuration we have.
I can add our own on a branch `ow2`
And the beta on `beta`

@valeriocos could you help me to push my local configuration to an `ow2` branch ?

**Comment by valeriocos** [comment]
Sure @mhow2 , have a look at this branch https://github.com/crossminer/scava-deployment/tree/ow2

**Comment by valeriocos** [comment]
@mhow2 if you are fine with the new `ow2` branch, can we close this issue?
