### ISSUE TITLE
Remove docker-compose using dockerhub images

### ISSUE THREAD

**Issue by borisbaldassari** [crossminer/scava-deployment#93]
Since the docker-compose file must be edited before being build they cannot be built automatically anymore. As a consequence the docker hub images have not been updated for a long time, and the docker-compose-dockerhub.yml file should be deleted from the repository.

**Comment by tdegueul** [comment]
Nice. Does this mean we can rename `docker-compose-build.yml` to `docker-compose.yml` to avoid having to specify it every time on the command line? ;)

**Comment by borisbaldassari** [comment]
Yep. I'll do that asap. :-D

**Comment by borisbaldassari** [comment]
Done. :-)
