### ISSUE TITLE
Merge to master?

### ISSUE THREAD

**Issue by borisbaldassari** [crossminer/scava-deployment#99]
We have a quite stable build here, maybe we could merge to master.. WDYT? 
Please vote in here and I'll do the merge when we have 3 thumbs up. :-)

**Comment by mhow2** [comment]
What build are you thinking ?

**Comment by tdegueul** [comment]
> What build are you thinking ?

Merging `dev` into `master`. There's just nothing in the master `master` branch currently so that's just a free merge.

**Comment by mhow2** [comment]
OK, I realize that I am in scava-deployment... not scava. Well you have my thumb up. Anyway I'm using the `ow2` branch for the docker deployment so I'll merge the changes whenever it's needed.

**Comment by tdegueul** [comment]
Done.

**Comment by borisbaldassari** [comment]
Thanks @tdegueul! :-)
